/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datatypes.DtProfesor;
import datatypes.DtSocio;
import datatypes.DtUsuario;
import interfaces.IControlador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ConsultarUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarUsuarios
     */
    private IControlador icon;
    public ConsultarUsuarios(IControlador con) {
        initComponents();
        this.icon = con;
        
        tablaSocios();
    }
    
    public void tablaSocios(){
        DefaultTableModel modelo = new DefaultTableModel();
        ArrayList<DtSocio> list;
        list = icon.obtenerSocios();
        modelo.addColumn("Id");
        modelo.addColumn("NickName");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Email");
        
        for (DtSocio dtSocio : list) {
            modelo.addRow(new Object[]{dtSocio.getId(),dtSocio.getNickname(),dtSocio.getNombre(), dtSocio.getApellido(), dtSocio.getEmail()});
        }
        
        tablaSocios.setModel(modelo);
    }
    public void tablaProfes(){
        DefaultTableModel modelo = new DefaultTableModel();
        ArrayList<DtProfesor> list;
        list = icon.obtenerProfes();
        modelo.addColumn("Id");
        modelo.addColumn("NickName");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Email");
        
        for (DtProfesor dtProfe : list) {
            modelo.addRow(new Object[]{dtProfe.getId(),dtProfe.getNickname(),dtProfe.getNombre(), dtProfe.getApellido(), dtProfe.getEmail()});
        }
        
        tablaProfes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbUsuarios = new javax.swing.JTabbedPane();
        panelSocios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        lblInfoExtra = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPaneSocio = new javax.swing.JTextPane();
        panelProfes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProfes = new javax.swing.JTable();
        lblInfoExtra2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblInicio = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1120, 830));

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NickName", "Nombre", "Apellido", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSocios.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tablaSocios);

        lblInfoExtra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoExtra.setText("Información Extra:");

        jScrollPane3.setViewportView(txtPaneSocio);

        javax.swing.GroupLayout panelSociosLayout = new javax.swing.GroupLayout(panelSocios);
        panelSocios.setLayout(panelSociosLayout);
        panelSociosLayout.setHorizontalGroup(
            panelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
            .addGroup(panelSociosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelSociosLayout.createSequentialGroup()
                        .addComponent(lblInfoExtra)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSociosLayout.setVerticalGroup(
            panelSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSociosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoExtra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbUsuarios.addTab("Socios", panelSocios);

        tablaProfes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProfes);

        lblInfoExtra2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoExtra2.setText("Información Extra:");

        jScrollPane4.setViewportView(jTextPane1);

        javax.swing.GroupLayout panelProfesLayout = new javax.swing.GroupLayout(panelProfes);
        panelProfes.setLayout(panelProfesLayout);
        panelProfesLayout.setHorizontalGroup(
            panelProfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
            .addGroup(panelProfesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(panelProfesLayout.createSequentialGroup()
                        .addComponent(lblInfoExtra2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelProfesLayout.setVerticalGroup(
            panelProfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoExtra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbUsuarios.addTab("Profesores", panelProfes);

        lblInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Usuarios del Sistema");
        lblInicio.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbUsuarios))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblInfoExtra;
    private javax.swing.JLabel lblInfoExtra2;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JPanel panelProfes;
    private javax.swing.JPanel panelSocios;
    private javax.swing.JTabbedPane tabbUsuarios;
    private javax.swing.JTable tablaProfes;
    private javax.swing.JTable tablaSocios;
    private javax.swing.JTextPane txtPaneSocio;
    // End of variables declaration//GEN-END:variables
}
